#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera un baseline del esquema `public` de PROD (onems-dev sehbnpgzqljrsqimwyuz)
por introspeccion via la Management API de Supabase (HTTPS, solo SELECT).
Salida: supabase/migrations/00000000000000_baseline_prod_schema.sql

Orden seguro: sequences -> tables -> constraints -> indexes -> functions ->
views (topo-sort por dependencia) -> triggers -> RLS/policies -> grants.
`SET check_function_bodies=false` permite crear funciones antes de sus tablas
y con referencias a cron/net (stubeadas en el shim de test).
"""
import json, os, sys, urllib.request, urllib.error, collections

REF = "sehbnpgzqljrsqimwyuz"
ROOT = r"c:\Users\fernandezi\projects\ONEMS"
TOKEN_FILE = os.path.join(ROOT, "one4claudecodekey.txt")
OUT = os.path.join(ROOT, "supabase", "migrations", "00000000000000_baseline_prod_schema.sql")

with open(TOKEN_FILE, "r", encoding="utf-8") as f:
    TOKEN = f.read().strip()

def q(sql):
    body = json.dumps({"query": sql}).encode("utf-8")
    req = urllib.request.Request(
        f"https://api.supabase.com/v1/projects/{REF}/database/query",
        data=body, method="POST",
        headers={"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json",
                 "User-Agent": "curl/8.4.0", "Accept": "*/*"})
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            return json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        print("HTTP ERROR", e.code, e.read().decode("utf-8")[:500], file=sys.stderr)
        raise

out = []
def w(s=""): out.append(s)

# -------- Sequences --------
seqs = q("""
select c.relname,
       format_type(s.seqtypid, null) as typ,
       s.seqstart, s.seqincrement, s.seqmin, s.seqmax
from pg_sequence s
join pg_class c on c.oid = s.seqrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname='public'
order by c.relname;
""")

# -------- Tables (col defs) --------
tables = q("""
select c.relname as tbl,
  string_agg(
    quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
    || case a.attidentity
         when 'd' then ' GENERATED BY DEFAULT AS IDENTITY'
         when 'a' then ' GENERATED ALWAYS AS IDENTITY'
         else '' end
    || case when a.attnotnull then ' NOT NULL' else '' end
    || case when pg_get_expr(ad.adbin, ad.adrelid) is not null and a.attidentity=''
            then ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end
  , E',\n  ' order by a.attnum) as cols
from pg_class c
join pg_namespace n on n.oid=c.relnamespace
join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped
left join pg_attrdef ad on ad.adrelid=c.oid and ad.adnum=a.attnum
where n.nspname='public' and c.relkind='r'
group by c.relname
order by c.relname;
""")

# -------- Constraints (PK/UNIQUE/CHECK/FK) --------
cons = q("""
select c.relname as tbl, con.conname,
       pg_get_constraintdef(con.oid) as def,
       con.contype
from pg_constraint con
join pg_class c on c.oid=con.conrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public'
order by case con.contype when 'p' then 0 when 'u' then 1 when 'c' then 2 else 3 end, c.relname, con.conname;
""")

# -------- Indexes (excluye los que respaldan constraints) --------
idx = q("""
select c.relname as tbl, i.relname as idxname, pg_get_indexdef(ix.indexrelid) as def
from pg_index ix
join pg_class c on c.oid=ix.indrelid
join pg_class i on i.oid=ix.indexrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public'
  and not exists (select 1 from pg_constraint con where con.conindid=ix.indexrelid)
order by c.relname, i.relname;
""")

# -------- Functions --------
funcs = q("""
select p.proname, pg_get_functiondef(p.oid) as def
from pg_proc p
join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public'
order by p.proname;
""")

# -------- Views + deps para topo-sort --------
views = q("""
select c.relname as viewname, pg_get_viewdef(c.oid, true) as def
from pg_class c
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relkind='v'
order by c.relname;
""")
vdeps = q("""
select v.relname as viewname, d.relname as depends_on
from pg_rewrite r
join pg_class v on v.oid=r.ev_class
join pg_namespace nv on nv.oid=v.relnamespace and nv.nspname='public'
join pg_depend dep on dep.objid=r.oid and dep.refclassid='pg_class'::regclass
join pg_class d on d.oid=dep.refobjid and d.relkind='v'
join pg_namespace nd on nd.oid=d.relnamespace and nd.nspname='public'
where v.relname <> d.relname
group by v.relname, d.relname;
""")

# -------- Triggers --------
trigs = q("""
select pg_get_triggerdef(t.oid) as def
from pg_trigger t
join pg_class c on c.oid=t.tgrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and not t.tgisinternal
order by c.relname, t.tgname;
""")

# -------- RLS enabled tables + policies --------
rls = q("""
select c.relname
from pg_class c join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relkind='r' and c.relrowsecurity
order by c.relname;
""")
pols = q("""
select schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
from pg_policies where schemaname='public'
order by tablename, policyname;
""")

# -------- Grants a roles Supabase --------
grants = q("""
select grantee, table_name, string_agg(privilege_type, ', ' order by privilege_type) as privs
from information_schema.role_table_grants
where table_schema='public' and grantee in ('anon','authenticated','service_role')
group by grantee, table_name
order by table_name, grantee;
""")

# ================= ENSAMBLADO =================
w("-- ============================================================")
w("-- BASELINE — esquema `public` capturado de PROD (onems-dev sehbnpgzqljrsqimwyuz)")
w("-- Generado por introspeccion (pg_catalog) via Management API. NO editar a mano.")
w("-- Reemplaza las 130 migraciones historicas (archivadas). Forward-only desde aqui.")
w("-- Extensiones (pg_cron/pg_net/pgcrypto/uuid-ossp/supabase_vault) las gestiona")
w("-- Supabase; en validacion local las cubre el bootstrap-shim.")
w("-- ============================================================")
w("SET check_function_bodies = false;")
w("SET search_path = public, extensions;")
w("")

w("-- ---------- SEQUENCES ----------")
for s in seqs:
    w(f"CREATE SEQUENCE IF NOT EXISTS public.{s['relname']} AS {s['typ']} "
      f"START WITH {s['seqstart']} INCREMENT BY {s['seqincrement']};")
w("")

w("-- ---------- TABLES ----------")
for t in tables:
    w(f"CREATE TABLE public.{t['tbl']} (\n  {t['cols']}\n);")
w("")

w("-- ---------- CONSTRAINTS ----------")
for c in cons:
    w(f"ALTER TABLE public.{c['tbl']} ADD CONSTRAINT {c['conname']} {c['def']};")
w("")

w("-- ---------- INDEXES ----------")
for i in idx:
    w(f"{i['def']};")
w("")

w("-- ---------- FUNCTIONS ----------")
for fn in funcs:
    w(f"{fn['def']};")
    w("")

# topo-sort views
dep = collections.defaultdict(set)
allv = [v['viewname'] for v in views]
vdef = {v['viewname']: v['def'] for v in views}
for d in vdeps:
    if d['viewname'] in vdef and d['depends_on'] in vdef:
        dep[d['viewname']].add(d['depends_on'])
ordered, seen = [], set()
def visit(name, stack):
    if name in seen: return
    for dd in sorted(dep.get(name, ())):
        if dd not in stack:
            visit(dd, stack | {name})
    seen.add(name); ordered.append(name)
for v in allv:
    visit(v, set())

w("-- ---------- VIEWS (orden por dependencia) ----------")
for name in ordered:
    w(f"CREATE OR REPLACE VIEW public.{name} AS\n{vdef[name]};")
    w("")

w("-- ---------- TRIGGERS ----------")
for t in trigs:
    w(f"{t['def']};")
w("")

w("-- ---------- ROW LEVEL SECURITY ----------")
for r in rls:
    w(f"ALTER TABLE public.{r['relname']} ENABLE ROW LEVEL SECURITY;")
w("")

w("-- ---------- POLICIES ----------")
def parse_pg_array(v):
    if isinstance(v, list):
        return v
    s = str(v).strip()
    if s.startswith("{") and s.endswith("}"):
        s = s[1:-1]
    return [x.strip().strip('"') for x in s.split(",") if x.strip()]

for p in pols:
    roles = ", ".join(parse_pg_array(p['roles']))
    cmd = p['cmd']
    line = f"CREATE POLICY {json.dumps(p['policyname'])} ON public.{p['tablename']}"
    line += f" AS {'PERMISSIVE' if p['permissive']=='PERMISSIVE' else 'RESTRICTIVE'}"
    line += f" FOR {cmd} TO {roles}"
    if p['qual'] is not None:
        line += f"\n  USING ({p['qual']})"
    if p['with_check'] is not None:
        line += f"\n  WITH CHECK ({p['with_check']})"
    w(line + ";")
w("")

w("-- ---------- GRANTS (roles Supabase) ----------")
for g in grants:
    w(f"GRANT {g['privs']} ON public.{g['table_name']} TO {g['grantee']};")
w("")

w("RESET check_function_bodies;")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")

print(f"OK baseline escrito: {OUT}")
print(f"  seqs={len(seqs)} tables={len(tables)} constraints={len(cons)} "
      f"indexes={len(idx)} funcs={len(funcs)} views={len(views)} "
      f"triggers={len(trigs)} rls={len(rls)} policies={len(pols)} grants={len(grants)}")
