/**
 * Utility functions for exporting data to CSV and PDF
 */

export function downloadCSV(data: any[], filename: string) {
  if (data.length === 0) {
    alert('No data to export')
    return
  }

  // Get headers from first object
  const headers = Object.keys(data[0])
  
  // Create CSV content
  const csvContent = [
    headers.join(','), // Header row
    ...data.map(row => 
      headers.map(header => {
        const value = row[header]
        // Escape commas and quotes
        if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
          return `"${value.replace(/"/g, '""')}"`
        }
        return value
      }).join(',')
    )
  ].join('\n')

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  
  link.setAttribute('href', url)
  link.setAttribute('download', filename)
  link.style.visibility = 'hidden'
  
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

export function generatePurchaseOrderPDF(requirements: any[], accountName: string = 'ONEMS'): string {
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Purchase Order - ${accountName}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 20px;
    }
    .header h1 {
      color: #2563eb;
      margin: 0;
      font-size: 28px;
    }
    .header p {
      margin: 5px 0;
      color: #666;
    }
    .info-section {
      margin-bottom: 30px;
    }
    .info-section h3 {
      color: #2563eb;
      margin-bottom: 10px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    th {
      background-color: #2563eb;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: bold;
    }
    td {
      padding: 10px 12px;
      border-bottom: 1px solid #e5e7eb;
    }
    tr:hover {
      background-color: #f9fafb;
    }
    .total-row {
      font-weight: bold;
      background-color: #f3f4f6;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
    .status-badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: bold;
    }
    .status-pending {
      background-color: #fef3c7;
      color: #92400e;
    }
    .status-ordered {
      background-color: #dbeafe;
      color: #1e40af;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>PURCHASE ORDER</h1>
    <p><strong>${accountName}</strong></p>
    <p>Date: ${date}</p>
  </div>

  <div class="info-section">
    <h3>Material Requirements</h3>
    <p>The following materials are required for upcoming allocation plans:</p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Material Code</th>
        <th>Material Name</th>
        <th>Quantity Needed</th>
        <th>Net Quantity</th>
        <th>Unit</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
`

  let totalQuantity = 0
  let totalNetQuantity = 0

  requirements.forEach(req => {
    totalQuantity += req.quantity_needed || 0
    totalNetQuantity += req.net_quantity || 0
    
    const statusClass = req.status === 'pending' ? 'status-pending' : 'status-ordered'
    
    html += `
      <tr>
        <td><strong>${req.material_code}</strong></td>
        <td>${req.material_name}</td>
        <td>${req.quantity_needed}</td>
        <td><strong>${req.net_quantity}</strong></td>
        <td>${req.unit_measure}</td>
        <td><span class="status-badge ${statusClass}">${req.status.toUpperCase()}</span></td>
      </tr>
`
  })

  html += `
      <tr class="total-row">
        <td colspan="2"><strong>TOTAL</strong></td>
        <td><strong>${totalQuantity}</strong></td>
        <td><strong>${totalNetQuantity}</strong></td>
        <td colspan="2"></td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by ONEMS Stock Management System</p>
    <p>${date}</p>
  </div>
</body>
</html>
`

  return html
}

export function generatePackingListPDF(shipments: any[], accountName: string = 'ONEMS'): string {
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })

  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Packing List - ${accountName}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 3px solid #10b981;
      padding-bottom: 20px;
    }
    .header h1 {
      color: #10b981;
      margin: 0;
      font-size: 28px;
    }
    .header p {
      margin: 5px 0;
      color: #666;
    }
    .shipment-section {
      margin-bottom: 40px;
      page-break-inside: avoid;
    }
    .shipment-header {
      background-color: #f0fdf4;
      padding: 15px;
      border-left: 4px solid #10b981;
      margin-bottom: 15px;
    }
    .shipment-header h3 {
      margin: 0 0 10px 0;
      color: #10b981;
    }
    .shipment-header p {
      margin: 5px 0;
      font-size: 14px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }
    th {
      background-color: #10b981;
      color: white;
      padding: 10px;
      text-align: left;
      font-weight: bold;
    }
    td {
      padding: 8px 10px;
      border-bottom: 1px solid #e5e7eb;
    }
    tr:hover {
      background-color: #f9fafb;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>PACKING LIST</h1>
    <p><strong>${accountName}</strong></p>
    <p>Date: ${date}</p>
  </div>
`

  shipments.forEach((shipment, index) => {
    const expectedDate = shipment.expected_date 
      ? new Date(shipment.expected_date).toLocaleDateString('en-US')
      : 'Not specified'

    html += `
  <div class="shipment-section">
    <div class="shipment-header">
      <h3>Shipment #${index + 1} - ${shipment.panelist_name || 'Unknown Panelist'}</h3>
      <p><strong>Panelist Code:</strong> ${shipment.panelist_code || 'N/A'}</p>
      <p><strong>Expected Date:</strong> ${expectedDate}</p>
      <p><strong>Total Items:</strong> ${shipment.items?.length || 0}</p>
    </div>

    <table>
      <thead>
        <tr>
          <th>Material Code</th>
          <th>Material Name</th>
          <th>Quantity</th>
          <th>Unit</th>
        </tr>
      </thead>
      <tbody>
`

    if (shipment.items && shipment.items.length > 0) {
      shipment.items.forEach((item: any) => {
        html += `
        <tr>
          <td><strong>${item.material_code || 'N/A'}</strong></td>
          <td>${item.material_name || 'Unknown'}</td>
          <td><strong>${item.quantity_sent}</strong></td>
          <td>${item.unit_measure || 'un'}</td>
        </tr>
`
      })
    }

    html += `
      </tbody>
    </table>
  </div>
`
  })

  html += `
  <div class="footer">
    <p>Generated by ONEMS Stock Management System</p>
    <p>${date}</p>
  </div>
</body>
</html>
`

  return html
}

export function printPDF(htmlContent: string, filename: string) {
  // Open print window with HTML content
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    alert('Please allow popups to print the document')
    return
  }

  printWindow.document.write(htmlContent)
  printWindow.document.close()
  
  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.print()
  }
}
